// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://zhtepcmalsjmsipqrmzg.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_mLdhqLFDPtvyWV2YcCfbcw_tJK22jUi";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);