
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuaysbxfqcuyzbtwttvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1YXlzYnhmcWN1eXpidHd0dHZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDI2MzUsImV4cCI6MjA2MzQ3ODYzNX0.yyUFL8peegXBUyaaHtkAgreDeLBRTFfJSxOjwT3GN0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
